version: '3'

services:
  nginx:
    image: nginx:1.13.5-alpine
    # build: ./docker/nginx
    # container_name: "drafan-web"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
  app:
    image: php:fpm
    # build: ./docker/app
    # container_name: "drafan-app"
    volumes:
      - ./src:/var/www:cached
    working_dir: /var/www/drafan