version: '3'

services:
  nginx:
    image: nginx:1.13.5-alpine
    # build: ./docker/nginx
    # container_name: "drafan-web"
    ports:
      - "80:80"
      - "443:443"
    # logging:
    #   driver: awslogs
    #   options:
    #     awslogs-group: /ecs/cli/tutorial
    #     awslogs-region: ap-northeast-1
    #     awslogs-stream-prefix: nginx