version: '3'

services:
  nginx:
    build: ./docker/nginx
    container_name: "drafan-web"
    ports:
      - "8008:80"
      - "443:443"
    volumes:
      - ./src:/var/www:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
    depends_on:
      - app
  app:
    build: ./docker/app
    container_name: "drafan-app"
    volumes:
      - ./src:/var/www:cached
    working_dir: /var/www/drafan